syntax = "All"
column_width = 170
line_endings = "Unix"
indent_type = "Tabs"
indent_width = 2
quote_style = "AutoPreferSingle"
call_parentheses = "Input"
collapse_simple_statement = "Never"
space_after_function_names = "Never"

[sort_requires]
enabled = true
